### ISSUE TITLE
the sample run failed 

### ISSUE THREAD

**Issue by heheda123123** [xmake-examples/wxWidgets-scaffold#1]
run the command in readme.md
```
git clone https://github.com/xmake-examples/wxWidgets-scaffold.git
cd wxWidgets-scaffold
xmake -y
xmake run
```
the program compile success, but run will notice the  below error
![image](https://github.com/xmake-examples/wxWidgets-scaffold/assets/97490782/cfdddbb9-3cca-4fe0-a164-3427472aeae4)

**Comment by waruqi** [comment]
运行时问题，你得到 wxWidgets 那边去问，这边也是用它现成提供的预编译库来 link，没做其他特别处理。 这边只处理编译期问题

**Comment by heheda123123** [comment]
wxwidget说代码没啥问题，就这么几行代码我感觉也不是她的问题。估计还是xmake-repo中wxwidgets包构建过程有什么问题

**Comment by waruqi** [comment]
> wxwidget说代码没啥问题，就这么几行代码我感觉也不是她的问题。估计还是xmake-repo中wxwidgets包构建过程有什么问题

<img width="564" alt="image" src="https://github.com/xmake-examples/wxWidgets-scaffold/assets/151335/7ddffd83-3a6c-4f1f-aec1-6b7f5dd2e37e">

直接拉的他们官方 release 下提供的预构建包。。xmake 都没去构建。

**Comment by heheda123123** [comment]
嗯，我之前看过wxwidget包知道是直接用的编译好的lib。但是还是有些不一样的，比如传的宏

**Comment by waruqi** [comment]
> 嗯，我之前看过wxwidget包知道是直接用的编译好的lib。但是还是有些不一样的，比如传的宏

如果只是宏影响，你可以自己从 -v 看完整定义，然后到 wxwidget 那边去对下。。

**Comment by heheda123123** [comment]
貌似还真是xmake包的问题，直接用的官方提供的lib没错，但是链接得太多了
https://groups.google.com/g/wx-dev/c/2cRFiXftB10

![image](https://github.com/xmake-examples/wxWidgets-scaffold/assets/97490782/d1d3631a-a78a-4785-b9fb-9926b71c287c)
官方提供的包里面混着调试版的lib，然后链接的时候两种版本都链接进去了

可能得这里改下，复制lib的时候只复制非调试版的
https://github.com/xmake-io/xmake-repo/blob/12c517ff0014d6f7dac0472d83e32a3b992f3952/packages/w/wxwidgets/xmake.lua#L68

**Comment by waruqi** [comment]
你可以来个 pr 改进下，区分 debug/release

**Comment by heheda123123** [comment]
试了下，不知道为啥debug版的老是有问题跑不起来，也不报错，先pr个能跑的win release的好了

https://github.com/xmake-io/xmake-repo/pull/2160

**Comment by heheda123123** [comment]
已解决
